// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csm-hbnfs/nfs (interfaces: Unmounter)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUnmounter is a mock of Unmounter interface.
type MockUnmounter struct {
	ctrl     *gomock.Controller
	recorder *MockUnmounterMockRecorder
}

// MockUnmounterMockRecorder is the mock recorder for MockUnmounter.
type MockUnmounterMockRecorder struct {
	mock *MockUnmounter
}

// NewMockUnmounter creates a new mock instance.
func NewMockUnmounter(ctrl *gomock.Controller) *MockUnmounter {
	mock := &MockUnmounter{ctrl: ctrl}
	mock.recorder = &MockUnmounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnmounter) EXPECT() *MockUnmounterMockRecorder {
	return m.recorder
}

// Unmount mocks base method.
func (m *MockUnmounter) Unmount(arg0 string, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmount indicates an expected call of Unmount.
func (mr *MockUnmounterMockRecorder) Unmount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmount", reflect.TypeOf((*MockUnmounter)(nil).Unmount), arg0, arg1)
}
